[package]
name = "stereokit-sys"
license = "MIT"
description = "Low-Level Rust bindings around the StereoKitC library for XR"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "StereoKitC"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
bindgen = "0.59.2"