[build]
target = "x86_64-unknown-linux-musl"
linker = "rust-lld"
rustflags = ["-Clink-self-contained=on"]

[env]
CC = "clang"
CXX = "clang++"
# CC = "/usr/bin/zig cc"
# CXX = "/usr/bin/zig c++"
# CC = "\"zig\" cc -target x86_64-linux-musl"
# CXX = "\"zig\" c++ -target x86_64-linux-musl"
# LDFLAGS = "-Wl,-z,stack-size=1024768"